#!/bin/env python
"""
This file is generated by zops.anatomy.
"""
import os

try:
    # For pip >= 10.0
    from pip._internal.req import parse_requirements
except ImportError:
    # For pip < 10.0
    from pip.req import parse_requirements
from setuptools import setup

# REFERENCE: http://stackoverflow.com/questions/14399534
install_requires = [
    str(i.req)
    for i in parse_requirements(
        os.path.join(os.path.dirname(__file__), 'requirements/base.include'),
        session='hack',  # Bogus value
    )
]

setup_kwargs = dict(
    name='nexxera.nix',
    url='https://github.com/nexxera/nix',
    description=".",
    long_description='''.''',
    classifiers=[
        'Development Status :: 3 - Alpha',
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.7',
    ],
    keywords=[],
)

# Versioning
setup_kwargs['use_scm_version'] = {"root": "..", "relative_to": __file__}

# Packages (using namespace)
setup_kwargs['include_package_data'] = True
setup_kwargs['packages'] = ['nexxera', 'nexxera.nix']
setup_kwargs['namespace_packages'] = ['nexxera']

# Dependencies
setup_kwargs['install_requires'] = install_requires
setup_kwargs['dependency_links'] = []
setup_kwargs['setup_requires'] = ['setuptools_scm']
setup_kwargs['tests_require'] = []


setup(**setup_kwargs)
