---
marks:
  - usefixtures:
    - flask_live_url

test_name: Testing nix API

stages:
  - name: Smoke test for ping
    request:
      url: '{flask_live_url}/ping'
      method: GET
    response:
      status_code: 200

  - name: Delete all users.
    request:
      url: '{flask_live_url}/users/'
      method: DELETE
    response:
      status_code: 200

  - name: List all users (empty).
    request:
      url: '{flask_live_url}/users/'
      method: GET
    response:
      status_code: 200

  - name: Create an user.
    request:
      url: '{flask_live_url}/users/'
      method: POST
      headers:
          content-type: application/json
      json:
        name: "Alpha"
        cnpj: "11111111111111"
    response:
      status_code: 201
      body:
        id: 1
        nome: "Alpha"
        cnpj: "11111111111111"

  - name: List all users (one).
    request:
      url: '{flask_live_url}/users/'
      method: GET
    response:
      status_code: 200
      body:
        - id: 1
          nome: "Alpha"
          cnpj: "11111111111111"

  - name: Delete all transactions.
    request:
      url: '{flask_live_url}/transactions/'
      method: DELETE
    response:
      status_code: 200

  - name: Create the first transaction.
    request:
      url: '{flask_live_url}/transactions/'
      method: POST
      headers:
          content-type: application/json
      json:
          user_id: 1
          amount: 100.00
    response:
      status_code: 201
      body:
          id: 1
          usuario_id: 1
          valor: 100.00

  - name: Create the second transaction.
    request:
      url: '{flask_live_url}/transactions/'
      method: POST
      headers:
          content-type: application/json
      json:
          user_id: 1
          amount: 10.00
    response:
      status_code: 201
      body:
          id: 2
          usuario_id: 1
          valor: 10.00

  - name: Lists the (two) transactions.
    request:
      url: '{flask_live_url}/transactions/'
    response:
      status_code: 200
      body:
        - id: 1
          usuario_id: 1
          valor: 100.00
        - id: 2
          usuario_id: 1
          valor: 10.00

  - name: Delete the second transaction.
    request:
        url: '{flask_live_url}/transactions/2/'
        method: DELETE
    response:
        status_code: 200
        body: {}

  - name: Lists the (remaining) transactions.
    request:
      url: '{flask_live_url}/transactions/'
    response:
      status_code: 200
      body:
        - id: 1
          usuario_id: 1
          valor: 100.00
