---
marks:
  - usefixtures:
    - flask_live_url

test_name: Testing nix API

stages:

  # Testing users

  - name: List all users (empty).
    request:
      url: '{flask_live_url}/api/users'
      method: GET
    response:
      status_code: 200
      body:
        num_results: 0
        objects: []
        page: 1
        total_pages: 0

  - name: Create an user.
    request:
      url: '{flask_live_url}/api/users'
      method: POST
      headers:
          content-type: application/json
      json:
        name: "Alpha"
        cnpj: "11111111111111"
    response:
      status_code: 201
      body:
        id: 1
        name: "Alpha"
        cnpj: "11111111111111"

  - name: List all users (one).
    request:
      url: '{flask_live_url}/api/users'
      method: GET
    response:
      status_code: 200
      body:
        num_results: 1
        objects:
          - id: 1
            name: "Alpha"
            cnpj: "11111111111111"
        page: 1
        total_pages: 1

  - name: Get one specific user.
    request:
      url: '{flask_live_url}/api/users/1'
    response:
      status_code: 200
      body:
          id: 1
          name: "Alpha"
          cnpj: "11111111111111"

  # Testing transactions

  - name: List all transactions (zero).
    request:
      url: '{flask_live_url}/api/transactions'
      method: GET
    response:
      status_code: 200
      body:
        num_results: 0
        objects: []
        page: 1
        total_pages: 0

  - name: Create the first transaction.
    request:
      url: '{flask_live_url}/api/transactions'
      method: POST
      headers:
          content-type: application/json
      json:
          user_id: 1
          creditor_name: Alpha
          creditor_bank: ABank
          creditor_agency: AAgency
          creditor_account: '001'
          debtor_name: Bravo
          debtor_bank: BBank
          debtor_agency: BAgency
          debtor_account: '002'
          amount: 100.00
          type: 'IGNORED'
    response:
      status_code: 201
      body:
          id: 1
          user_id: 1
          creditor_name: Alpha
          creditor_bank: ABank
          creditor_agency: AAgency
          creditor_account: '001'
          debtor_name: Bravo
          debtor_bank: BBank
          debtor_agency: BAgency
          debtor_account: '002'
          amount: 100.00
          type: 'DOC'

  - name: Create the second transaction.
    request:
      url: '{flask_live_url}/api/transactions'
      method: POST
      headers:
          content-type: application/json
      json:
          user_id: 1
          creditor_name: Charlie
          creditor_bank: CBank
          creditor_agency: CAgency
          creditor_account: '003'
          debtor_name: Bravo
          debtor_bank: BBank
          debtor_agency: BAgency
          debtor_account: '002'
          amount: 10.00
          type: 'IGNORED'
    response:
      status_code: 201
      body:
          id: 2
          user_id: 1
          creditor_name: Charlie
          creditor_bank: CBank
          creditor_agency: CAgency
          creditor_account: '003'
          debtor_name: Bravo
          debtor_bank: BBank
          debtor_agency: BAgency
          debtor_account: '002'
          amount: 10.00
          type: 'DOC'

  - name: Get one specific transaction.
    request:
      url: '{flask_live_url}/api/transactions/2'
    response:
      status_code: 200
      body:
          id: 2
          user_id: 1
          creditor_name: Charlie
          creditor_bank: CBank
          creditor_agency: CAgency
          creditor_account: '003'
          debtor_name: Bravo
          debtor_bank: BBank
          debtor_agency: BAgency
          debtor_account: '002'
          amount: 10.00
          type: 'DOC'

  - name: Lists the transactions (two).
    request:
      url: '{flask_live_url}/api/transactions'
    response:
      status_code: 200
      body:
        num_results: 2
        objects:
          - id: 1
            user_id: 1
            creditor_name: Alpha
            creditor_bank: ABank
            creditor_agency: AAgency
            creditor_account: '001'
            debtor_name: Bravo
            debtor_bank: BBank
            debtor_agency: BAgency
            debtor_account: '002'
            amount: 100.00
            type: 'DOC'
          - id: 2
            user_id: 1
            creditor_name: Charlie
            creditor_bank: CBank
            creditor_agency: CAgency
            creditor_account: '003'
            debtor_name: Bravo
            debtor_bank: BBank
            debtor_agency: BAgency
            debtor_account: '002'
            amount: 10.00
            type: 'DOC'
        page: 1
        total_pages: 1
        total_amount: 110.00

  - name: Delete the second transaction.
    request:
        url: '{flask_live_url}/api/transactions/2'
        method: DELETE
    response:
        status_code: 204
        body: {}

  - name: Get one specific transaction (deleted).
    request:
      url: '{flask_live_url}/api/transactions/2'
    response:
      status_code: 404

  - name: Lists the transactions (one).
    request:
      url: '{flask_live_url}/api/transactions'
    response:
      status_code: 200
      body:
        num_results: 1
        objects:
          - id: 1
            user_id: 1
            creditor_name: Alpha
            creditor_bank: ABank
            creditor_agency: AAgency
            creditor_account: '001'
            debtor_name: Bravo
            debtor_bank: BBank
            debtor_agency: BAgency
            debtor_account: '002'
            amount: 100.00
            type: 'DOC'
        page: 1
        total_pages: 1
        total_amount: 100.00

  - name: Creates a transaction with error (max_amount).
    request:
      url: '{flask_live_url}/api/transactions'
      method: POST
      headers:
          content-type: application/json
      json:
          user_id: 1
          creditor_name: Delta
          creditor_bank: DBank
          creditor_agency: DAgency
          creditor_account: '004'
          debtor_name: Bravo
          debtor_bank: BBank
          debtor_agency: BAgency
          debtor_account: '002'
          amount: 100000.99
          type: 'IGNORED'
    response:
      status_code: 201
      body:
          # TODO: This is bad. The deleted transaction id is being reused.
          id: 2
          user_id: 1
          creditor_name: Delta
          creditor_bank: DBank
          creditor_agency: DAgency
          creditor_account: '004'
          debtor_name: Bravo
          debtor_bank: BBank
          debtor_agency: BAgency
          debtor_account: '002'
          amount: 100000.99
          type: 'DOC'
          status: 'ERRO'

  - name: Creates one more transaction.
    request:
      url: '{flask_live_url}/api/transactions'
      method: POST
      headers:
          content-type: application/json
      json:
          user_id: 1
          creditor_name: Echo
          creditor_bank: EBank
          creditor_agency: EAgency
          creditor_account: '005'
          debtor_name: Alpha
          debtor_bank: ABank
          debtor_agency: AAgency
          debtor_account: '001'
          amount: 1.00
          type: 'IGNORED'
    response:
      status_code: 201
      body:
          id: 3
          user_id: 1
          creditor_name: Echo
          creditor_bank: EBank
          creditor_agency: EAgency
          creditor_account: '005'
          debtor_name: Alpha
          debtor_bank: ABank
          debtor_agency: AAgency
          debtor_account: '001'
          amount: 1.00
          type: 'DOC'
          status: 'OK'

  - name: Creates a CC transaction.
    request:
      url: '{flask_live_url}/api/transactions'
      method: POST
      headers:
          content-type: application/json
      json:
          user_id: 1
          creditor_name: Foxtrot
          creditor_bank: ABank
          creditor_agency: AAgency
          creditor_account: '006'
          debtor_name: Alpha
          debtor_bank: ABank
          debtor_agency: AAgency
          debtor_account: '001'
          amount: 10000.00
          type: 'IGNORED'
    response:
      status_code: 201
      body:
          id: 4
          user_id: 1
          creditor_name: Foxtrot
          creditor_bank: ABank
          creditor_agency: AAgency
          creditor_account: '006'
          debtor_name: Alpha
          debtor_bank: ABank
          debtor_agency: AAgency
          debtor_account: '001'
          amount: 10000.00
          type: 'CC'
          status: 'OK'

  - name: Lists the transactions (four).
    request:
      url: '{flask_live_url}/api/transactions'
    response:
      status_code: 200
      body:
        num_results: 4
        objects:
          - id: 1
            user_id: 1
            creditor_name: Alpha
            creditor_bank: ABank
            creditor_agency: AAgency
            creditor_account: '001'
            debtor_name: Bravo
            debtor_bank: BBank
            debtor_agency: BAgency
            debtor_account: '002'
            amount: 100.00
            type: 'DOC'
            status: 'OK'
          - id: 2
            user_id: 1
            creditor_name: Delta
            creditor_bank: DBank
            creditor_agency: DAgency
            creditor_account: '004'
            debtor_name: Bravo
            debtor_bank: BBank
            debtor_agency: BAgency
            debtor_account: '002'
            amount: 100000.99
            type: 'DOC'
            status: 'ERRO'
          - id: 3
            user_id: 1
            creditor_name: Echo
            creditor_bank: EBank
            creditor_agency: EAgency
            creditor_account: '005'
            debtor_name: Alpha
            debtor_bank: ABank
            debtor_agency: AAgency
            debtor_account: '001'
            amount: 1.00
            type: 'DOC'
            status: 'OK'
          - id: 4
            user_id: 1
            creditor_name: Foxtrot
            creditor_bank: ABank
            creditor_agency: AAgency
            creditor_account: '006'
            debtor_name: Alpha
            debtor_bank: ABank
            debtor_agency: AAgency
            debtor_account: '001'
            amount: 10000.00
            type: 'CC'
            status: 'OK'
        page: 1
        total_pages: 1
        total_amount: 110101.99

  - name: Lists the transactions (filtered by creditor).
    request:
      url: '{flask_live_url}/api/transactions'
      params:
        q: '{{"filters":[{{"name":"creditor_name", "op":"eq", "val":"Alpha"}}]}}'
    response:
      status_code: 200
      body:
        num_results: 1
        objects:
          - id: 1
            user_id: 1
            creditor_name: Alpha
            creditor_bank: ABank
            creditor_agency: AAgency
            creditor_account: '001'
            debtor_name: Bravo
            debtor_bank: BBank
            debtor_agency: BAgency
            debtor_account: '002'
            amount: 100.00
            type: 'DOC'
            status: 'OK'
        page: 1
        total_pages: 1
        total_amount: 100.00

  - name: Lists the transactions (filtered by debtor).
    request:
      url: '{flask_live_url}/api/transactions'
      params:
        q: '{{"filters":[{{"name":"debtor_name", "op":"eq", "val":"Alpha"}}]}}'
    response:
      status_code: 200
      body:
        num_results: 2
        objects:
          - id: 3
            user_id: 1
            creditor_name: Echo
            creditor_bank: EBank
            creditor_agency: EAgency
            creditor_account: '005'
            debtor_name: Alpha
            debtor_bank: ABank
            debtor_agency: AAgency
            debtor_account: '001'
            amount: 1.00
            type: 'DOC'
            status: 'OK'
          - id: 4
            user_id: 1
            creditor_name: Foxtrot
            creditor_bank: ABank
            creditor_agency: AAgency
            creditor_account: '006'
            debtor_name: Alpha
            debtor_bank: ABank
            debtor_agency: AAgency
            debtor_account: '001'
            amount: 10000.00
            type: 'CC'
            status: 'OK'
        page: 1
        total_pages: 1
        total_amount: 10001.00
