openapi: '3.0.0'
info:
  description: Nix
  version: 0.1.0
  title: Nix

paths:
  /ping:
    get:
      operationId: 'nexxera.nix.api.ping'
      summary: 'Ping'
      responses:
        200:
          description: Successful

  /users/:
    get:
      operationId: 'nexxera.nix.api.get_users'
      summary: 'Returns the users optionally filtering them.'
      responses:
        200:
          description: Successful

  /transactions/:
    get:
      operationId: 'nexxera.nix.api.get_transactions'
      summary: 'Returns the transactions optionally filtering them.'
      responses:
        200:
          description: Successful

    post:
      operationId: 'nexxera.nix.api.post_transaction'
      summary: 'Creates a new transaction.'
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/components/schemas/TransactionCreate'
      responses:
        201:
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransactionCreate'

#  /transactions/{tid}:
#    get:
#      operationId: 'nexxera.nix.api.get_transaction'
#      summary: 'Returns the transactions optionally filtering them.'
#      parameters:
#        - name: tid
#          in: path
#          type: string
#          required: true
#      responses:
#        200:
#          description: Successful response

#    delete:
#      operationId: 'nexxera.nix.api.delete_transaction'
#      summary: 'Deletes a transaction.'
#      parameters:
#        - name: tid
#          in: path
#          type: int
#          required: true

components:
  schemas:
    TransactionCreate:
      type: object
      properties:
        amount:
          type: decimal
