openapi: '3.0.0'
info:
  description: Nix
  version: 0.1.0
  title: Nix

paths:
  /ping:
    get:
      operationId: 'nexxera.nix.api.ping'
      summary: 'Ping'
      responses:
        200:
          description: 'Successful'

  /users/:
    delete:
      operationId: 'nexxera.nix.api.delete_users'
      summary: 'Deletes all users.'
      responses:
        200:
          description: 'Successful'
    get:
      operationId: 'nexxera.nix.api.get_users'
      summary: 'Returns the users optionally filtering them.'
      responses:
        200:
          description: 'Successful'
    post:
      operationId: 'nexxera.nix.api.post_users'
      summary: 'Creates a new user.'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserCreate'
      responses:
        201:
          description: 'Created'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserCreate'

  /users/{uid}/:
    get:
      operationId: 'nexxera.nix.api.get_user'
      summary: 'Returns a specific user.'
      parameters:
        - name: uid
          in: path
          required: true
          schema:
            type: integer
      responses:
        200:
          description: 'Successful'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserCreate'

  /transactions/:
    delete:
      operationId: 'nexxera.nix.api.delete_transactions'
      summary: 'Deletes all transactions.'
      responses:
        200:
          description: 'Successful'
    get:
      operationId: 'nexxera.nix.api.get_transactions'
      summary: 'Returns the transactions optionally filtering them.'
      responses:
        200:
          description: 'Successful'

    post:
      operationId: 'nexxera.nix.api.post_transaction'
      summary: 'Creates a new transaction.'
      responses:
        201:
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransactionCreate'

  /transactions/{tid}/:
    delete:
      operationId: 'nexxera.nix.api.delete_transaction'
      summary: 'Delete a transaction'
      parameters:
        - name: tid
          in: path
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Successful response
    get:
      operationId: 'nexxera.nix.api.get_transaction'
      summary: 'Returns the transactions optionally filtering them.'
      parameters:
        - name: tid
          in: path
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Successful response

components:
  schemas:
    UserCreate:
      type: object
      properties:
        name:
          type: string
        cnpj:
          type: string

    TransactionCreate:
      type: object
      properties:
        amount:
          type: decimal
