#!/bin/bash
"""
This file is generated by zops.anatomy.
"""

if [ "$1" = "run-web" ]; then
    PARAMS="--http-socket :80 --module $2"
    shift 2
fi

if [ "$1" = "run-app" ]; then
    PARAMS="--uwsgi-socket :80 --module $2"
    shift 2
fi

if [ "$NEW_RELIC_LICENSE_KEY" != "" ]; then
    echo "INFO: Using new-relic wrapper."
    EXECUTABLE="newrelic-admin run-program uwsgi"
else
    EXECUTABLE="uwsgi"
fi

if [ "$PARAMS" != "" ]; then
    if [ "$2" = "" ]; then
        echo "Usage: docker run (...) run-web|run-app <UWSGI_MODULE>"
    fi
    CMD_LINE="$EXECUTABLE --ini /srv/uwsgi.ini $PARAMS $*"
    echo CMD_LINE: $CMD_LINE
    exec $CMD_LINE
fi

exec "$@"
